# Generated by Django 5.0.6 on 2024-06-23 19:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscription_type", models.CharField(max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("requests_left", models.IntegerField(default=1000)),
                ("expiry", models.BigIntegerField(default=None)),
            ],
        ),
    ]
